name: "Formatting Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Prettier
      run: npx prettier --check .

    - name: Run Prettier to fix formatting issues
      if: failure()
      run: npx prettier --write .

    - name: Comment on pull request with fixed formatting
      if: failure()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx prettier --write .
        gh pr comment ${{ github.event.pull_request.number }} --body "### Prettier Formatting Fixes\n\`\`\`\n$(npx prettier --write .)\n\`\`\`"
